### ISSUE TITLE
Test process portail  echoue

### ISSUE THREAD

**Issue by mpasteur** [Noethys/Noethys#21]
sous linux le test des process python ouverts pour detecer si run.py est en cours de fonctionnement échoue avec l'erreur:
```
Traceback (most recent call last):
  File "/root/Noethys/noethys/Dlg/DLG_Portail_config.py", line 845, in OnBoutonOutils
    if len(self.GetListeProcess()) > 0 :
  File "/root/Noethys/noethys/Dlg/DLG_Portail_config.py", line 960, in GetListeProcess
    if len(cmdline) > 0 and "run.py" in cmdline[1] :
IndexError: list index out of range

```

**Comment by Noethys** [comment]
J'ai fait une petite modification. Voir autre discussion.
