### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by thsfo** [Noethys/Noethys#40]
Le logiciel me demande de signaler ceci à l'auteur (erreur au moment de saisir  une unité de remplissage): 
`## 19/09/2017 15:30:19 | 1.2.1.2 | wxPython 3.0.2.0 gtk2 (classic) | linux2 Linux 4.9.0-3-686 i686 ##
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 16765, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/lib/masked/maskededit.py", line 5637, in _fixSelection
    elif sel_start > self._goEnd(getPosOnly=True):
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/lib/masked/maskededit.py", line 4578, in _goEnd
    char = text[i]
IndexError: string index out of range
`

**Comment by thsfo** [comment]
J'ai l'impression que le problème vient de la manière dont il est permis d'écrire dans les champs  horaires par exemple ici : https://framapic.org/3QAf0waWcKbJ/9iYJLDxlmtcj.png

**Comment by Noethys** [comment]
Bonjour,
Oui, je crois que la saisie des champs préformatés est assez sensible dans Linux mais noralement cela devrait fonctionner en utilisant bien le format 08:30.
Ivan
